import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layout/Navbar";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.variable} antialiased`}
        style={{ fontFamily: 'var(--font-montserrat), Montserrat, sans-serif' }}
      >
        {/* App wrapper */}
        <div className="flex flex-col min-h-screen">
          {/* Global navigation bar */}
          <Navbar />

          {/* Main page content */}
          <main className="flex-1">{children}</main>
        </div>
      </body>
    </html>
  );
}
